# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /github/workspace/conda.recipes, last modified Fri Sep 25 18:37:44 2020
# ------------------------------------------------

package:
    name: malaria
    version: 0.0.4
source:
    path: /github/workspace
build:
    noarch: python
    preserve_egg_dir: true
    script: python setup.py install --record=record.txt
    string: py_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py37hc8dfbb8_0
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - python 3.7.8 h6f2ec95_1_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py37hc8dfbb8_1
        - sqlite 3.33.0 h4cf870e_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - fiona
        - gdal
        - netcdf4
        - numpy
        - python
        - rasterio
about:
    author: Riley Hales
    description: An app for running disease spread models developed at John Hopkins
        University and using global datasets from NASA LDAS
    dev_url: https://github.com/BYU-Hydroinformatics/malaria
    license: BSD 3-Clause License
extra:
    copy_test_source_files: true
    final: true
    keywords: Tethys,App,Services,Cool
    recipe-maintainers:
        - TethysAppWarehouse
