name: main

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: echo $AGENT_TOOLSDIRECTORY
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python -m pip install --upgrade pyyaml
      - name: Gen Build Command
        run: |
          python ./conda.recipes/getChannels.py > build_command.txt
      - name: publish-to-conda
        uses: rfun/conda-package-publish-action@master
        with:
          subDir: "conda.recipes"
          AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
