# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /github/workspace/conda.recipes, last modified Thu Nov  5 02:29:37 2020
# ------------------------------------------------

package:
    name: newgrace
    version: 2.0.0
source:
    path: /github/workspace
build:
    noarch: python
    preserve_egg_dir: true
    script: python setup.py install --record=record.txt
    string: py_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py37he5f6b98_2
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_2
        - openssl 1.1.1h h516909a_0
        - pip 20.2.4 py_0
        - python 3.7.8 h6f2ec95_1_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py37he5f6b98_2
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    run:
        - fiona
        - gdal
        - geojson
        - netCDF4
        - numpy
        - pyshp
        - python
        - rtree
        - shapely
about:
    author: Travis McStraw
    description: The GRACE application is a visualization tool for GRACE global satellite
        data. It also provides visualization for global surface water, soil moisture,
        and groundwater data.
    dev_url: null
    license: null
extra:
    author_email: travis.mcstraw@gmail.com
    copy_test_source_files: true
    final: true
    keywords: null
    recipe-maintainers:
        - TethysAppWarehouse
